allowBuilds:
  '@swc/core': false
  cbor-extract: false
  esbuild: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@ai-sdk/openai@4.0.66'
  - '@ai-sdk/provider-utils@5.0.40'
  - '@ai-sdk/provider@4.0.14'
