import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import LogoutButton from "@/components/LogoutButton";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import QueryProviders from "@/components/QueryProviders";
import PerformanceClock from "@/components/PerformanceClock";
import { MusicPlayer } from "@/components/MusicPlayer";
import { TooltipProvider } from "@/components/ui/tooltip";
import { HeaderNav } from "@/components/HeaderNav";
import { SearchAll } from "@/components/SearchAll";
import { UserCenter } from "@/components/UserCenter";
import { MobileSheetNav } from "@/components/MobileSheetNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const audios = [
  {
    name: "Alarm Clock",
    src: "/audio/alarmClock.wav",
    id: 0,
  },
  {
    name: "好久不见",
    src: "/audio/haojiubujian.mp3",
    id: 1,
  },
  {
    name: "红梅花儿开",
    src: "/audio/hongmeihuaerkai.mp3",
    id: 2,
  },
  {
    name: "New",
    src: "/audio/new.mp3",
    id: 3,
  },
  {
    name: "宁愿",
    src: "/audio/ningyuan.mp3",
    id: 4,
  },
  {
    name: "Shine",
    src: "/audio/shine.mp3",
    id: 5,
  },
  {
    name: "Starts",
    src: "/audio/starts.mp3",
    id: 6,
  },
];
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="zh-CN"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <body className="h-screen flex flex-col justify-between bg-white dark:bg-gray-700 bg-[radial-gradient(#e5e7eb_1px,transparent_1px),linear-gradient(to_bottom,#e5e7eb,transparent)]! bg-size-[24px_24px]!"> */}
      <body>
        <div
          id="global_anln"
          className="h-screen flex flex-col justify-between bg-white dark:bg-gray-700 bg-[radial-gradient(#b1cacb_1px,transparent_1px)]! dark:bg-[radial-gradient(#32393a_1px,transparent_1px)]! bg-size-[24px_24px]!"
        >
          <div className="flex-1 flex flex-col justify-between items-center bg-linear-to-br from-transparent via-35% to-[white] dark:to-[black]">
            <QueryProviders>
              <TooltipProvider>
                <>
                  <header className="fixed z-90 top-0 w-full p-4 max-h-24 bg-white dark:bg-gray-700/40 border-b border-white/40 dark:border-black/40 backdrop-blur-md shadow-xl shadow-[#d3d5d848] dark:shadow-[#2e2f2f48]">
                    <MobileSheetNav />
                    <HeaderNav />
                  </header>

                  <main className="w-full mt-18">
                    <div id="global-loading"></div>
                    {children}
                    {/* sonner 提示 */}
                    <Toaster className="bg-white dark:bg-gray-700" />
                  </main>
                  <footer className="w-full">
                    <div className="w-full py-8 bg-white dark:bg-gray-700 shadow-xl  drop-shadow-[0_-4px_12px_#d3d5d848] dark:drop-shadow-[0_-4px_12px_#2e2f2f48] border-t border-slate-100 dark:border-slate-800 text-center text-sm text-slate-400">
                      <p>©2026 个人作品集 · Next.js + TailwindCSS 构建</p>
                    </div>
                  </footer>
                </>
              </TooltipProvider>
            </QueryProviders>
          </div>
        </div>
        {/* 音乐播放器 */}
        <MusicPlayer className="fixed z-90 bottom-6 right-6" audios={audios} />
      </body>
    </html>
  );
}
